extends RefCounted
# Generated by tools/index_arcade_atlases.py; artwork is unchanged.
const DATA := {
  "abhi": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 244,
    "frames": [
      {
        "region": [
          35,
          14,
          203,
          243
        ],
        "exclusions": [],
        "pivot_x": 109.26653033401499,
        "floor_y": 243
      },
      {
        "region": [
          300,
          14,
          187,
          243
        ],
        "exclusions": [],
        "pivot_x": 100.2702503681885,
        "floor_y": 243
      },
      {
        "region": [
          592,
          14,
          124,
          243
        ],
        "exclusions": [],
        "pivot_x": 62.753859598019176,
        "floor_y": 243
      },
      {
        "region": [
          803,
          14,
          202,
          243
        ],
        "exclusions": [],
        "pivot_x": 109.02935821574874,
        "floor_y": 243
      },
      {
        "region": [
          1068,
          14,
          186,
          243
        ],
        "exclusions": [],
        "pivot_x": 100.10115394058425,
        "floor_y": 243
      },
      {
        "region": [
          1360,
          14,
          124,
          243
        ],
        "exclusions": [],
        "pivot_x": 62.98889862693545,
        "floor_y": 243
      },
      {
        "region": [
          25,
          284,
          211,
          225
        ],
        "exclusions": [],
        "pivot_x": 111.24431599229285,
        "floor_y": 225
      },
      {
        "region": [
          290,
          284,
          206,
          222
        ],
        "exclusions": [],
        "pivot_x": 108.90935430463577,
        "floor_y": 222
      },
      {
        "region": [
          559,
          276,
          189,
          205
        ],
        "exclusions": [],
        "pivot_x": 97.52409882543543,
        "floor_y": 231.5
      },
      {
        "region": [
          787,
          284,
          216,
          225
        ],
        "exclusions": [],
        "pivot_x": 116.12740569668972,
        "floor_y": 225
      },
      {
        "region": [
          1056,
          284,
          208,
          222
        ],
        "exclusions": [],
        "pivot_x": 110.79281314168384,
        "floor_y": 222
      },
      {
        "region": [
          1327,
          278,
          188,
          217
        ],
        "exclusions": [],
        "pivot_x": 95.80766192733017,
        "floor_y": 229.5
      },
      {
        "region": [
          14,
          523,
          197,
          244
        ],
        "exclusions": [],
        "pivot_x": 97.30807850296668,
        "floor_y": 244
      },
      {
        "region": [
          282,
          523,
          201,
          244
        ],
        "exclusions": [],
        "pivot_x": 98.44757354790045,
        "floor_y": 244
      },
      {
        "region": [
          557,
          507,
          141,
          198
        ],
        "exclusions": [],
        "pivot_x": 71.82433566433565,
        "floor_y": 260.0
      },
      {
        "region": [
          768,
          526,
          229,
          241
        ],
        "exclusions": [],
        "pivot_x": 121.74341689488097,
        "floor_y": 241
      },
      {
        "region": [
          1026,
          528,
          270,
          239
        ],
        "exclusions": [],
        "pivot_x": 106.48863636363626,
        "floor_y": 239
      },
      {
        "region": [
          1317,
          524,
          198,
          243
        ],
        "exclusions": [],
        "pivot_x": 99.80938349954658,
        "floor_y": 243
      },
      {
        "region": [
          35,
          767,
          142,
          239
        ],
        "exclusions": [],
        "pivot_x": 71.27554705757383,
        "floor_y": 239
      },
      {
        "region": [
          238,
          787,
          274,
          219
        ],
        "exclusions": [],
        "pivot_x": 94.55461862782676,
        "floor_y": 219
      },
      {
        "region": [
          550,
          767,
          131,
          239
        ],
        "exclusions": [],
        "pivot_x": 65.68892012180834,
        "floor_y": 239
      },
      {
        "region": [
          766,
          786,
          202,
          222
        ],
        "exclusions": [],
        "pivot_x": 77.69991564740621,
        "floor_y": 222
      },
      {
        "region": [
          1004,
          780,
          224,
          228
        ],
        "exclusions": [
          [
            0.791015625,
            0.9267578125,
            0.7994791666666666,
            0.9580078125
          ]
        ],
        "pivot_x": 80.70428189116865,
        "floor_y": 228
      },
      {
        "region": [
          1216,
          916,
          298,
          97
        ],
        "exclusions": [],
        "pivot_x": 147.29716399506788,
        "floor_y": 97
      }
    ]
  },
  "anant": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 239,
    "frames": [
      {
        "region": [
          46,
          21,
          201,
          247
        ],
        "exclusions": [],
        "pivot_x": 106.24357405140759,
        "floor_y": 247
      },
      {
        "region": [
          311,
          21,
          178,
          246
        ],
        "exclusions": [],
        "pivot_x": 102.58954909397386,
        "floor_y": 246
      },
      {
        "region": [
          597,
          20,
          123,
          249
        ],
        "exclusions": [],
        "pivot_x": 53.26283987915406,
        "floor_y": 249
      },
      {
        "region": [
          817,
          21,
          205,
          247
        ],
        "exclusions": [],
        "pivot_x": 105.3055911224925,
        "floor_y": 247
      },
      {
        "region": [
          1079,
          20,
          179,
          247
        ],
        "exclusions": [],
        "pivot_x": 103.28998384491115,
        "floor_y": 247
      },
      {
        "region": [
          1361,
          20,
          114,
          249
        ],
        "exclusions": [],
        "pivot_x": 49.210407239819006,
        "floor_y": 249
      },
      {
        "region": [
          27,
          294,
          221,
          223
        ],
        "exclusions": [],
        "pivot_x": 109.04645076872751,
        "floor_y": 223
      },
      {
        "region": [
          302,
          294,
          204,
          223
        ],
        "exclusions": [],
        "pivot_x": 94.63955509210984,
        "floor_y": 223
      },
      {
        "region": [
          568,
          281,
          183,
          200
        ],
        "exclusions": [],
        "pivot_x": 85.41326067211628,
        "floor_y": 236.0
      },
      {
        "region": [
          789,
          291,
          225,
          227
        ],
        "exclusions": [],
        "pivot_x": 112.79944289693594,
        "floor_y": 227
      },
      {
        "region": [
          1061,
          292,
          212,
          224
        ],
        "exclusions": [],
        "pivot_x": 104.11886920980919,
        "floor_y": 224
      },
      {
        "region": [
          1328,
          281,
          187,
          211
        ],
        "exclusions": [],
        "pivot_x": 88.66398158803213,
        "floor_y": 236.0
      },
      {
        "region": [
          25,
          540,
          196,
          239
        ],
        "exclusions": [],
        "pivot_x": 96.18515797207935,
        "floor_y": 239
      },
      {
        "region": [
          283,
          540,
          197,
          239
        ],
        "exclusions": [],
        "pivot_x": 97.66829268292685,
        "floor_y": 239
      },
      {
        "region": [
          558,
          524,
          146,
          177
        ],
        "exclusions": [],
        "pivot_x": 84.10584752035527,
        "floor_y": 255.0
      },
      {
        "region": [
          767,
          550,
          221,
          229
        ],
        "exclusions": [],
        "pivot_x": 121.63460104399701,
        "floor_y": 229
      },
      {
        "region": [
          1019,
          550,
          271,
          230
        ],
        "exclusions": [],
        "pivot_x": 107.6417716022579,
        "floor_y": 230
      },
      {
        "region": [
          1306,
          543,
          200,
          236
        ],
        "exclusions": [],
        "pivot_x": 101.89744552967704,
        "floor_y": 236
      },
      {
        "region": [
          44,
          780,
          140,
          231
        ],
        "exclusions": [],
        "pivot_x": 76.04768355459225,
        "floor_y": 231
      },
      {
        "region": [
          243,
          806,
          271,
          206
        ],
        "exclusions": [],
        "pivot_x": 92.63591722202739,
        "floor_y": 206
      },
      {
        "region": [
          572,
          779,
          122,
          232
        ],
        "exclusions": [],
        "pivot_x": 67.07969877627863,
        "floor_y": 232
      },
      {
        "region": [
          779,
          801,
          173,
          210
        ],
        "exclusions": [],
        "pivot_x": 71.72268647477563,
        "floor_y": 210
      },
      {
        "region": [
          966,
          867,
          326,
          143
        ],
        "exclusions": [
          [
            0.8118489583333334,
            0.9287109375,
            0.8411458333333334,
            0.98046875
          ]
        ],
        "pivot_x": 142.19929213177238,
        "floor_y": 143
      },
      {
        "region": [
          1248,
          932,
          273,
          75
        ],
        "exclusions": [],
        "pivot_x": 145.59651118695479,
        "floor_y": 75
      }
    ]
  },
  "anug": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 239,
    "frames": [
      {
        "region": [
          51,
          19,
          183,
          240
        ],
        "exclusions": [],
        "pivot_x": 83.38446676970634,
        "floor_y": 240
      },
      {
        "region": [
          309,
          19,
          175,
          240
        ],
        "exclusions": [],
        "pivot_x": 73.60678488820355,
        "floor_y": 240
      },
      {
        "region": [
          591,
          19,
          125,
          243
        ],
        "exclusions": [],
        "pivot_x": 43.888543689320386,
        "floor_y": 243
      },
      {
        "region": [
          810,
          19,
          188,
          240
        ],
        "exclusions": [],
        "pivot_x": 89.4292101341282,
        "floor_y": 240
      },
      {
        "region": [
          1078,
          19,
          174,
          240
        ],
        "exclusions": [],
        "pivot_x": 72.78715953307392,
        "floor_y": 240
      },
      {
        "region": [
          1358,
          18,
          118,
          244
        ],
        "exclusions": [],
        "pivot_x": 41.47025264873673,
        "floor_y": 244
      },
      {
        "region": [
          28,
          290,
          211,
          226
        ],
        "exclusions": [],
        "pivot_x": 105.98833097595474,
        "floor_y": 226
      },
      {
        "region": [
          300,
          290,
          194,
          227
        ],
        "exclusions": [],
        "pivot_x": 83.6166842661035,
        "floor_y": 227
      },
      {
        "region": [
          569,
          279,
          177,
          194
        ],
        "exclusions": [],
        "pivot_x": 84.10726865193726,
        "floor_y": 237.5
      },
      {
        "region": [
          787,
          292,
          206,
          224
        ],
        "exclusions": [],
        "pivot_x": 98.31615842972315,
        "floor_y": 224
      },
      {
        "region": [
          1060,
          290,
          197,
          227
        ],
        "exclusions": [],
        "pivot_x": 87.51023890784973,
        "floor_y": 227
      },
      {
        "region": [
          1337,
          281,
          176,
          199
        ],
        "exclusions": [],
        "pivot_x": 80.92444583203246,
        "floor_y": 235.5
      },
      {
        "region": [
          23,
          540,
          201,
          239
        ],
        "exclusions": [],
        "pivot_x": 99.67571587950911,
        "floor_y": 239
      },
      {
        "region": [
          285,
          540,
          193,
          239
        ],
        "exclusions": [],
        "pivot_x": 90.46251768033949,
        "floor_y": 239
      },
      {
        "region": [
          570,
          526,
          134,
          189
        ],
        "exclusions": [],
        "pivot_x": 59.58486238532112,
        "floor_y": 253.0
      },
      {
        "region": [
          771,
          546,
          217,
          233
        ],
        "exclusions": [],
        "pivot_x": 103.64573570759137,
        "floor_y": 233
      },
      {
        "region": [
          1019,
          546,
          270,
          231
        ],
        "exclusions": [],
        "pivot_x": 102.04358353510906,
        "floor_y": 231
      },
      {
        "region": [
          1307,
          540,
          191,
          236
        ],
        "exclusions": [],
        "pivot_x": 96.62495385751208,
        "floor_y": 236
      },
      {
        "region": [
          43,
          782,
          132,
          227
        ],
        "exclusions": [],
        "pivot_x": 73.64668664668665,
        "floor_y": 227
      },
      {
        "region": [
          258,
          806,
          257,
          204
        ],
        "exclusions": [],
        "pivot_x": 77.42659974905894,
        "floor_y": 204
      },
      {
        "region": [
          574,
          779,
          114,
          231
        ],
        "exclusions": [],
        "pivot_x": 61.968238993710656,
        "floor_y": 231
      },
      {
        "region": [
          778,
          805,
          174,
          204
        ],
        "exclusions": [],
        "pivot_x": 75.04293116210215,
        "floor_y": 204
      },
      {
        "region": [
          968,
          867,
          295,
          135
        ],
        "exclusions": [
          [
            0.8151041666666666,
            0.9462890625,
            0.822265625,
            0.97265625
          ]
        ],
        "pivot_x": 133.18700787401576,
        "floor_y": 135
      },
      {
        "region": [
          1253,
          933,
          268,
          63
        ],
        "exclusions": [],
        "pivot_x": 138.32043416705983,
        "floor_y": 63
      }
    ]
  },
  "bib": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 244,
    "frames": [
      {
        "region": [
          35,
          12,
          209,
          265
        ],
        "exclusions": [],
        "pivot_x": 117.22630761263594,
        "floor_y": 265
      },
      {
        "region": [
          309,
          12,
          193,
          265
        ],
        "exclusions": [],
        "pivot_x": 103.5081163859112,
        "floor_y": 265
      },
      {
        "region": [
          595,
          12,
          105,
          265
        ],
        "exclusions": [],
        "pivot_x": 53.03882809742322,
        "floor_y": 265
      },
      {
        "region": [
          807,
          12,
          208,
          265
        ],
        "exclusions": [],
        "pivot_x": 101.27118232580722,
        "floor_y": 265
      },
      {
        "region": [
          1080,
          12,
          200,
          265
        ],
        "exclusions": [],
        "pivot_x": 104.40772271207061,
        "floor_y": 265
      },
      {
        "region": [
          1369,
          12,
          118,
          265
        ],
        "exclusions": [],
        "pivot_x": 62.53488372093034,
        "floor_y": 265
      },
      {
        "region": [
          29,
          297,
          213,
          230
        ],
        "exclusions": [],
        "pivot_x": 121.11590296495956,
        "floor_y": 230
      },
      {
        "region": [
          303,
          296,
          206,
          231
        ],
        "exclusions": [],
        "pivot_x": 117.8697587256969,
        "floor_y": 231
      },
      {
        "region": [
          563,
          296,
          185,
          208
        ],
        "exclusions": [],
        "pivot_x": 107.07551127425279,
        "floor_y": 231.0
      },
      {
        "region": [
          789,
          294,
          216,
          233
        ],
        "exclusions": [],
        "pivot_x": 119.29168817759421,
        "floor_y": 233
      },
      {
        "region": [
          1070,
          294,
          208,
          233
        ],
        "exclusions": [],
        "pivot_x": 102.56167035398221,
        "floor_y": 233
      },
      {
        "region": [
          1331,
          294,
          181,
          210
        ],
        "exclusions": [],
        "pivot_x": 102.11432291666665,
        "floor_y": 233.0
      },
      {
        "region": [
          37,
          540,
          189,
          244
        ],
        "exclusions": [
          [
            0.064453125,
            0.759765625,
            0.08658854166666667,
            0.765625
          ]
        ],
        "pivot_x": 91.10565312843028,
        "floor_y": 244
      },
      {
        "region": [
          292,
          540,
          194,
          244
        ],
        "exclusions": [],
        "pivot_x": 95.30964467005077,
        "floor_y": 244
      },
      {
        "region": [
          561,
          527,
          142,
          202
        ],
        "exclusions": [],
        "pivot_x": 75.83360128617369,
        "floor_y": 257.0
      },
      {
        "region": [
          769,
          542,
          226,
          242
        ],
        "exclusions": [],
        "pivot_x": 125.99003735990038,
        "floor_y": 242
      },
      {
        "region": [
          1025,
          543,
          277,
          241
        ],
        "exclusions": [],
        "pivot_x": 103.25009402030832,
        "floor_y": 241
      },
      {
        "region": [
          1319,
          541,
          193,
          243
        ],
        "exclusions": [],
        "pivot_x": 94.82795698924724,
        "floor_y": 243
      },
      {
        "region": [
          46,
          779,
          136,
          235
        ],
        "exclusions": [
          [
            0.029947916666666668,
            0.7607421875,
            0.052083333333333336,
            0.7666015625
          ],
          [
            0.09635416666666667,
            0.7607421875,
            0.11848958333333333,
            0.7666015625
          ]
        ],
        "pivot_x": 69.57099314198628,
        "floor_y": 235
      },
      {
        "region": [
          253,
          799,
          281,
          216
        ],
        "exclusions": [],
        "pivot_x": 81.24779990736454,
        "floor_y": 216
      },
      {
        "region": [
          575,
          779,
          123,
          235
        ],
        "exclusions": [],
        "pivot_x": 61.993705743509054,
        "floor_y": 235
      },
      {
        "region": [
          765,
          801,
          192,
          213
        ],
        "exclusions": [],
        "pivot_x": 81.76622222222227,
        "floor_y": 213
      },
      {
        "region": [
          957,
          832,
          317,
          163
        ],
        "exclusions": [
          [
            0.7884114583333334,
            0.9267578125,
            0.8294270833333334,
            0.9716796875
          ]
        ],
        "pivot_x": 164.09570267131244,
        "floor_y": 163
      },
      {
        "region": [
          1212,
          932,
          307,
          78
        ],
        "exclusions": [],
        "pivot_x": 162.97924338801477,
        "floor_y": 78
      }
    ]
  },
  "ish": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 248,
    "frames": [
      {
        "region": [
          41,
          13,
          202,
          250
        ],
        "exclusions": [],
        "pivot_x": 100.23189680445617,
        "floor_y": 250
      },
      {
        "region": [
          305,
          14,
          184,
          249
        ],
        "exclusions": [],
        "pivot_x": 95.49592986850342,
        "floor_y": 249
      },
      {
        "region": [
          594,
          14,
          120,
          249
        ],
        "exclusions": [],
        "pivot_x": 50.474350205198334,
        "floor_y": 249
      },
      {
        "region": [
          800,
          13,
          208,
          250
        ],
        "exclusions": [],
        "pivot_x": 99.1784643071386,
        "floor_y": 250
      },
      {
        "region": [
          1071,
          14,
          186,
          249
        ],
        "exclusions": [],
        "pivot_x": 96.70343750000006,
        "floor_y": 249
      },
      {
        "region": [
          1367,
          14,
          115,
          249
        ],
        "exclusions": [],
        "pivot_x": 47.23293607800656,
        "floor_y": 249
      },
      {
        "region": [
          21,
          285,
          214,
          232
        ],
        "exclusions": [],
        "pivot_x": 113.67908148977875,
        "floor_y": 232
      },
      {
        "region": [
          292,
          285,
          198,
          232
        ],
        "exclusions": [],
        "pivot_x": 95.64784422809458,
        "floor_y": 232
      },
      {
        "region": [
          563,
          277,
          184,
          200
        ],
        "exclusions": [],
        "pivot_x": 87.60362280234415,
        "floor_y": 240.0
      },
      {
        "region": [
          779,
          285,
          218,
          231
        ],
        "exclusions": [],
        "pivot_x": 116.71788216973789,
        "floor_y": 231
      },
      {
        "region": [
          1045,
          285,
          210,
          232
        ],
        "exclusions": [],
        "pivot_x": 108.80382513661198,
        "floor_y": 232
      },
      {
        "region": [
          1333,
          277,
          179,
          213
        ],
        "exclusions": [],
        "pivot_x": 82.41809881847485,
        "floor_y": 240.0
      },
      {
        "region": [
          21,
          532,
          211,
          248
        ],
        "exclusions": [
          [
            0.06640625,
            0.75390625,
            0.08658854166666667,
            0.76171875
          ]
        ],
        "pivot_x": 96.56678135752267,
        "floor_y": 248
      },
      {
        "region": [
          283,
          534,
          201,
          245
        ],
        "exclusions": [],
        "pivot_x": 93.7331499312242,
        "floor_y": 245
      },
      {
        "region": [
          552,
          518,
          144,
          191
        ],
        "exclusions": [],
        "pivot_x": 75.82147435897434,
        "floor_y": 262.0
      },
      {
        "region": [
          767,
          534,
          214,
          246
        ],
        "exclusions": [],
        "pivot_x": 106.8253125,
        "floor_y": 246
      },
      {
        "region": [
          1019,
          535,
          279,
          245
        ],
        "exclusions": [],
        "pivot_x": 110.31232622798893,
        "floor_y": 245
      },
      {
        "region": [
          1301,
          532,
          201,
          248
        ],
        "exclusions": [],
        "pivot_x": 99.66210755362135,
        "floor_y": 248
      },
      {
        "region": [
          56,
          773,
          124,
          239
        ],
        "exclusions": [],
        "pivot_x": 61.52379587155963,
        "floor_y": 239
      },
      {
        "region": [
          258,
          788,
          268,
          225
        ],
        "exclusions": [],
        "pivot_x": 72.68703427719822,
        "floor_y": 225
      },
      {
        "region": [
          569,
          771,
          116,
          241
        ],
        "exclusions": [],
        "pivot_x": 58.367073880162934,
        "floor_y": 241
      },
      {
        "region": [
          769,
          799,
          180,
          213
        ],
        "exclusions": [],
        "pivot_x": 86.081178396072,
        "floor_y": 213
      },
      {
        "region": [
          958,
          852,
          320,
          160
        ],
        "exclusions": [
          [
            0.7884114583333334,
            0.9443359375,
            0.83203125,
            0.98828125
          ]
        ],
        "pivot_x": 147.3175046554934,
        "floor_y": 160
      },
      {
        "region": [
          1212,
          935,
          312,
          76
        ],
        "exclusions": [],
        "pivot_x": 179.41857841293722,
        "floor_y": 76
      }
    ]
  },
  "sab": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 239,
    "frames": [
      {
        "region": [
          27,
          20,
          226,
          244
        ],
        "exclusions": [],
        "pivot_x": 119.86996578046853,
        "floor_y": 244
      },
      {
        "region": [
          302,
          22,
          189,
          244
        ],
        "exclusions": [],
        "pivot_x": 101.73431845597105,
        "floor_y": 244
      },
      {
        "region": [
          603,
          20,
          129,
          246
        ],
        "exclusions": [],
        "pivot_x": 55.00099370652538,
        "floor_y": 246
      },
      {
        "region": [
          789,
          20,
          228,
          244
        ],
        "exclusions": [],
        "pivot_x": 125.60350235232613,
        "floor_y": 244
      },
      {
        "region": [
          1071,
          20,
          189,
          246
        ],
        "exclusions": [],
        "pivot_x": 102.44520752463427,
        "floor_y": 246
      },
      {
        "region": [
          1369,
          22,
          128,
          244
        ],
        "exclusions": [],
        "pivot_x": 54.01042367182254,
        "floor_y": 244
      },
      {
        "region": [
          23,
          293,
          234,
          223
        ],
        "exclusions": [],
        "pivot_x": 119.41393621668851,
        "floor_y": 223
      },
      {
        "region": [
          299,
          294,
          206,
          225
        ],
        "exclusions": [],
        "pivot_x": 97.01887705711522,
        "floor_y": 225
      },
      {
        "region": [
          546,
          282,
          208,
          203
        ],
        "exclusions": [],
        "pivot_x": 106.24086021505377,
        "floor_y": 236.0
      },
      {
        "region": [
          785,
          293,
          239,
          224
        ],
        "exclusions": [],
        "pivot_x": 124.34672257779744,
        "floor_y": 224
      },
      {
        "region": [
          1070,
          294,
          200,
          225
        ],
        "exclusions": [],
        "pivot_x": 89.15577119509703,
        "floor_y": 225
      },
      {
        "region": [
          1325,
          284,
          191,
          199
        ],
        "exclusions": [],
        "pivot_x": 92.81928306551299,
        "floor_y": 234.0
      },
      {
        "region": [
          25,
          533,
          216,
          239
        ],
        "exclusions": [],
        "pivot_x": 110.18579881656805,
        "floor_y": 239
      },
      {
        "region": [
          282,
          537,
          206,
          236
        ],
        "exclusions": [],
        "pivot_x": 103.17100130039012,
        "floor_y": 236
      },
      {
        "region": [
          554,
          525,
          153,
          191
        ],
        "exclusions": [],
        "pivot_x": 76.84676395939084,
        "floor_y": 248.0
      },
      {
        "region": [
          769,
          540,
          224,
          233
        ],
        "exclusions": [],
        "pivot_x": 122.29033119658118,
        "floor_y": 233
      },
      {
        "region": [
          1021,
          540,
          276,
          234
        ],
        "exclusions": [],
        "pivot_x": 109.25463851567497,
        "floor_y": 234
      },
      {
        "region": [
          1297,
          534,
          213,
          240
        ],
        "exclusions": [],
        "pivot_x": 118.89408932869742,
        "floor_y": 240
      },
      {
        "region": [
          45,
          778,
          140,
          232
        ],
        "exclusions": [],
        "pivot_x": 73.83608985435694,
        "floor_y": 232
      },
      {
        "region": [
          257,
          799,
          257,
          212
        ],
        "exclusions": [],
        "pivot_x": 84.87337224966325,
        "floor_y": 212
      },
      {
        "region": [
          562,
          775,
          135,
          237
        ],
        "exclusions": [],
        "pivot_x": 70.95505344995138,
        "floor_y": 237
      },
      {
        "region": [
          769,
          798,
          190,
          212
        ],
        "exclusions": [],
        "pivot_x": 77.91444966092854,
        "floor_y": 212
      },
      {
        "region": [
          972,
          830,
          325,
          180
        ],
        "exclusions": [
          [
            0.8033854166666666,
            0.9375,
            0.8444010416666666,
            0.9833984375
          ]
        ],
        "pivot_x": 148.60399529964752,
        "floor_y": 180
      },
      {
        "region": [
          1235,
          926,
          292,
          80
        ],
        "exclusions": [],
        "pivot_x": 167.3349794238684,
        "floor_y": 80
      }
    ]
  },
  "sup": {
    "size": [
      1536,
      1024
    ],
    "standing_height": 245,
    "frames": [
      {
        "region": [
          39,
          16,
          229,
          264
        ],
        "exclusions": [],
        "pivot_x": 111.3682135274492,
        "floor_y": 264
      },
      {
        "region": [
          308,
          19,
          185,
          258
        ],
        "exclusions": [],
        "pivot_x": 98.36712683347713,
        "floor_y": 258
      },
      {
        "region": [
          577,
          18,
          117,
          260
        ],
        "exclusions": [],
        "pivot_x": 59.484273589615555,
        "floor_y": 260
      },
      {
        "region": [
          801,
          18,
          225,
          262
        ],
        "exclusions": [],
        "pivot_x": 120.7431906614786,
        "floor_y": 262
      },
      {
        "region": [
          1077,
          19,
          190,
          258
        ],
        "exclusions": [],
        "pivot_x": 97.1652397260275,
        "floor_y": 258
      },
      {
        "region": [
          1352,
          18,
          124,
          260
        ],
        "exclusions": [],
        "pivot_x": 63.7400943396226,
        "floor_y": 260
      },
      {
        "region": [
          26,
          297,
          225,
          232
        ],
        "exclusions": [],
        "pivot_x": 117.75531621099145,
        "floor_y": 232
      },
      {
        "region": [
          300,
          295,
          201,
          232
        ],
        "exclusions": [],
        "pivot_x": 105.04296754250385,
        "floor_y": 232
      },
      {
        "region": [
          560,
          295,
          197,
          205
        ],
        "exclusions": [],
        "pivot_x": 105.74543849323129,
        "floor_y": 233.0
      },
      {
        "region": [
          796,
          298,
          223,
          231
        ],
        "exclusions": [],
        "pivot_x": 122.55004135649301,
        "floor_y": 231
      },
      {
        "region": [
          1077,
          297,
          196,
          229
        ],
        "exclusions": [],
        "pivot_x": 93.9688943640283,
        "floor_y": 229
      },
      {
        "region": [
          1330,
          297,
          189,
          200
        ],
        "exclusions": [],
        "pivot_x": 106.62699425654114,
        "floor_y": 231.0
      },
      {
        "region": [
          24,
          536,
          208,
          245
        ],
        "exclusions": [
          [
            0.0625,
            0.7568359375,
            0.07486979166666667,
            0.7626953125
          ]
        ],
        "pivot_x": 98.71547144754317,
        "floor_y": 245
      },
      {
        "region": [
          293,
          538,
          198,
          243
        ],
        "exclusions": [],
        "pivot_x": 91.22929631402587,
        "floor_y": 243
      },
      {
        "region": [
          566,
          525,
          138,
          196
        ],
        "exclusions": [],
        "pivot_x": 77.60844036697245,
        "floor_y": 256.0
      },
      {
        "region": [
          791,
          540,
          231,
          241
        ],
        "exclusions": [],
        "pivot_x": 127.40762999738695,
        "floor_y": 241
      },
      {
        "region": [
          1061,
          541,
          242,
          240
        ],
        "exclusions": [],
        "pivot_x": 89.3041871921182,
        "floor_y": 240
      },
      {
        "region": [
          1322,
          541,
          198,
          240
        ],
        "exclusions": [],
        "pivot_x": 99.09695201037607,
        "floor_y": 240
      },
      {
        "region": [
          37,
          776,
          145,
          234
        ],
        "exclusions": [
          [
            0.024088541666666668,
            0.7578125,
            0.03515625,
            0.763671875
          ]
        ],
        "pivot_x": 86.85142083897158,
        "floor_y": 234
      },
      {
        "region": [
          225,
          798,
          285,
          214
        ],
        "exclusions": [],
        "pivot_x": 96.43476923076923,
        "floor_y": 214
      },
      {
        "region": [
          565,
          776,
          143,
          234
        ],
        "exclusions": [],
        "pivot_x": 85.26842684268422,
        "floor_y": 234
      },
      {
        "region": [
          763,
          803,
          206,
          208
        ],
        "exclusions": [],
        "pivot_x": 90.76068921506067,
        "floor_y": 208
      },
      {
        "region": [
          1003,
          852,
          243,
          154
        ],
        "exclusions": [],
        "pivot_x": 115.86763148605723,
        "floor_y": 154
      },
      {
        "region": [
          1256,
          925,
          266,
          72
        ],
        "exclusions": [],
        "pivot_x": 141.5610983981694,
        "floor_y": 72
      }
    ]
  }
}
