"""Read-only indexing of movement artwork; preserves original generated PNGs."""
import json
from pathlib import Path
import numpy as np
from PIL import Image
from scipy import ndimage

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT / "assets/sprites/fighter/motion"
catalog = {}
for name in ["anug", "ish", "sab", "bib", "abhi", "sup", "anant"]:
    pixels = np.asarray(Image.open(ROOT / f"{name}.png").convert("RGBA"))
    h, w, _ = pixels.shape
    assert pixels[0, 0, 3] < 8, f"{name}: transparent background required"
    labels, _ = ndimage.label(pixels[:, :, 3] >= 128)
    counts = np.bincount(labels.ravel())
    frames = [None] * 16
    for number, bounds in enumerate(ndimage.find_objects(labels), 1):
        if counts[number] < 1000:
            continue
        ys, xs = bounds
        cy, cx = ndimage.center_of_mass(labels == number)
        index = min(3, int(cy * 4 / h)) * 4 + min(3, int(cx * 4 / w))
        assert frames[index] is None, (name, index, "multiple figures")
        body = labels[ys, xs] == number
        # Use the pelvis, avoiding arms and the broadest stride silhouette.
        hip_band = body[int(body.shape[0]*0.48):int(body.shape[0]*0.55)]
        pivot = float(np.where(hip_band)[1].mean())
        foreign = np.unique(labels[ys, xs])
        assert not any(other not in [0, number] and counts[other] >= 1000 for other in foreign), (name, index, "neighbor overlap")
        frames[index] = {"region": [xs.start, ys.start, xs.stop-xs.start, ys.stop-ys.start],
                         "pivot_x": pivot, "floor_y": ys.stop-ys.start, "exclusions": [],
                         "source": "motion", "bottom": ys.stop - (index//4)*h/4}
    assert all(frames), (name, "missing poses")
    widths = []
    for frame in frames[:8]:
        x, y, width, frame_height = frame["region"]
        legs = pixels[y+int(frame_height*0.7):y+frame_height, x:x+width, 3] >= 128
        foot_x = np.where(legs)[1]
        widths.append(int(foot_x.max()-foot_x.min()+1))
    for contact, passing in [(0, 2), (4, 6)]:
        assert widths[passing] < widths[contact]*0.75, (name, "passing pose must narrow on both steps")
    height = float(np.median([f["region"][3] for f in frames[:8]]))
    contact_floors = {row: max(frames[row*4+i]["bottom"] for i in range(3)) for row in [2, 3]}
    for index, frame in enumerate(frames):
        # Contact poses stay on the floor. Preserve a small explicit flight gap;
        # never auto-normalize every running frame down onto the floor.
        if index in [11, 15]:
            row = index // 4
            contact_floor = contact_floors[row]
            gap = max(height * 0.045, contact_floor - frame["bottom"])
            frame["floor_y"] += gap
        frame.pop("bottom")
        frame["standing_height"] = height
    catalog[name] = {"size": [w, h], "standing_height": height, "frames": frames}
    print(f"{name}: eight walk + eight run poses, transparent and isolated")
(PROJECT / "scripts/motion_sprite_regions.gd").write_text(
    "extends RefCounted\n# Generated by tools/index_motion_atlases.py; PNG pixels unchanged.\nconst DATA := " + json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
(ROOT / "preview-data.js").write_text("window.MOTION_DATA = " + json.dumps(catalog) + ";\n", encoding="utf-8")
