"""Read sprite alpha and write frame-region metadata; never modifies artwork.

Dependencies: Pillow, numpy, scipy. Run from the project root.
Connected silhouettes allow a kick to extend beyond its nominal grid cell
without clipping the foot. Refuse ambiguous frames or neighboring silhouettes.
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = Path(__file__).resolve().parents[1] / "assets/sprites/fighter/nepali"
catalog = {}

for path in sorted(ROOT.glob("*.png")):
    walking = path.stem in ("walk_cycles", "run_cycles")
    rows, cols = (7, 6) if walking else (4, 4)
    image = Image.open(path)
    assert image.mode == "RGBA", f"{path.name}: missing real transparency"
    alpha = np.asarray(image)[:, :, 3]
    assert alpha.min() == 0 and alpha.max() == 255
    labels, _ = ndimage.label(alpha > 64)
    sizes = np.bincount(labels.ravel())
    objects = ndimage.find_objects(labels)
    frames = [None] * (rows * cols)
    for label, bounds in enumerate(objects, start=1):
        if sizes[label] < 1000:
            continue
        ys, xs = bounds
        center = ndimage.center_of_mass(alpha > 64, labels, label)
        row = min(rows - 1, int(center[0] * rows / image.height))
        col = min(cols - 1, int(center[1] * cols / image.width))
        index = row * cols + col
        assert frames[index] is None, f"{path.name}: two silhouettes in frame {index}"
        nearby = labels[ys, xs]
        foreign = np.count_nonzero((nearby != label) & (nearby != 0))
        # Ignore tiny alpha-edge flecks; reject any substantial neighboring art.
        assert foreign < 32, f"{path.name}: neighboring figure overlaps frame {index}: {foreign} pixels"
        frames[index] = {
            "region": [xs.start, ys.start, xs.stop-xs.start, ys.stop-ys.start],
            "pivot_x": image.width * (col + 0.5) / cols - xs.start,
            "floor_y": ys.stop - ys.start,
        }
        if walking:
            torso = (labels[ys.start + int((ys.stop-ys.start)*0.35):ys.start + int((ys.stop-ys.start)*0.55), xs] == label)
            frames[index]["pivot_x"] = float(np.where(torso)[1].mean())
    assert all(frames), f"{path.name}: expected {rows * cols} distinct full-body frames"
    data = {"size": [image.width, image.height], "standing_height": frames[0]["region"][3], "frames": frames}
    catalog[path.stem] = data
    path.with_suffix(".json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"{path.stem}: RGBA / {len(frames)} isolated frames / atlas regions verified")

# A preloaded script also preserves metadata in Godot exports without needing
# a custom include filter for the human-readable JSON sidecars.
destination = ROOT.parents[3] / "scripts/fighter_sprite_regions.gd"
destination.write_text("extends RefCounted\n# Generated by tools/index_fighter_atlases.py; PNG pixels are unchanged.\nconst DATA := " + json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
