"""Index generated arcade sheets without modifying any image pixels.

The runtime shader keys their solid magenta backdrop. Connected components
allow authored fists/feet to extend past nominal cells without clipping.
"""
import json
from pathlib import Path
import numpy as np
from PIL import Image
from scipy import ndimage

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT / "assets/sprites/fighter/arcade"
CATALOG = {}
for path in sorted(ROOT.glob("*.png")):
    rgb = np.asarray(Image.open(path).convert("RGB"), dtype=np.float32) / 255.0
    h, w, _ = rgb.shape
    key = (np.minimum(rgb[:, :, 0], rgb[:, :, 2]) - rgb[:, :, 1] > 0.35) & (np.minimum(rgb[:, :, 0], rgb[:, :, 2]) > 0.6)
    labels, _ = ndimage.label(~key)
    counts = np.bincount(labels.ravel())
    cells = [None] * 24
    for number, bounds in enumerate(ndimage.find_objects(labels), 1):
        if counts[number] < 1000:
            continue
        ys, xs = bounds
        cy, cx = ndimage.center_of_mass(labels == number)
        index = min(3, int(cy * 4 / h)) * 6 + min(5, int(cx * 6 / w))
        assert cells[index] is None, f"{path.stem}: multiple figures in cell {index}"
        # Preserve the authored body origin, independent of extended limbs.
        torso = labels[ys.start + int((ys.stop-ys.start)*0.38):ys.start + int((ys.stop-ys.start)*0.52), xs] == number
        root_x = xs.start + float(np.where(torso)[1].mean())
        exclusions = []
        crop = labels[ys, xs]
        for other in np.unique(crop):
            if other == 0 or other == number or counts[other] < 1000:
                continue
            oy, ox = np.where(crop == other)
            left, right = max(0, int(ox.min())-1), min(crop.shape[1], int(ox.max())+2)
            top, bottom = max(0, int(oy.min())-1), min(crop.shape[0], int(oy.max())+2)
            def exclude(left, top, right, bottom):
                area = crop[top:bottom, left:right]
                if not np.any(area == other):
                    return
                if not np.any(area == number):
                    exclusions.append([(xs.start+left)/w, (ys.start+top)/h, (xs.start+right)/w, (ys.start+bottom)/h])
                elif right-left > bottom-top:
                    mid = (left+right)//2
                    exclude(left, top, mid, bottom)
                    exclude(mid, top, right, bottom)
                else:
                    mid = (top+bottom)//2
                    exclude(left, top, right, mid)
                    exclude(left, mid, right, bottom)
            exclude(left, top, right, bottom)
        assert len(exclusions) <= 16, (path.stem, index, len(exclusions))
        cells[index] = {"region": [xs.start, ys.start, xs.stop-xs.start, ys.stop-ys.start], "root_x": root_x, "bottom": ys.stop, "exclusions": exclusions}
    assert all(cells), f"{path.stem}: missing cells {[i for i, c in enumerate(cells) if c is None]}"
    standing_height = cells[12]["region"][3]
    run_floor = float(np.median([cells[i]["bottom"] for i in [6, 7, 9, 10]]))
    jump_floor = float(np.median([cells[i]["bottom"] for i in [12, 13, 15, 16, 17]]))
    for index, cell in enumerate(cells):
        x, y, width, height = cell["region"]
        # All walking poses use their actual planted foot. Running flights and
        # jumps retain height above the contact plane instead of snapping down.
        floor_y = cell["bottom"]
        if index in [8, 11]:
            floor_y = run_floor
        elif index == 14:
            floor_y = jump_floor
        cell["pivot_x"] = cell.pop("root_x") - x
        cell["floor_y"] = floor_y - y
        cell.pop("bottom")
    CATALOG[path.stem] = {"size": [w, h], "standing_height": standing_height, "frames": cells}
    print(f"{path.stem}: 24 isolated poses indexed")

(PROJECT / "scripts/arcade_sprite_regions.gd").write_text(
    "extends RefCounted\n# Generated by tools/index_arcade_atlases.py; artwork is unchanged.\nconst DATA := " + json.dumps(CATALOG, indent=2) + "\n", encoding="utf-8")
